{'src/*', [debug_info,
           {i, "src"},
           {i, "include"},
           {outdir, "ebin"}]}.
{'test/*', [debug_info,
           {i, "src"},
           {i, "test"},
           {i, "include"},
           {outdir, "ebin"}]}.